### ISSUE TITLE
Version 11 broke syntax highlighting.

### ISSUE THREAD

**Issue by jacargentina** [babel/babel-sublime#413] opened 2021-06-21 19:04 UTC
Just updated; my example.

<img width="848" alt="Captura de Pantalla 2021-06-21 a la(s) 16 02 40" src="https://user-images.githubusercontent.com/517228/122814170-37f4de80-d2aa-11eb-97d3-7ec6a4d37240.png">

consta in yellow, console in yellow. Wrong!

**Comment by Thom1729** [comment] 2021-06-21 19:10
Looks like a bug in arrow function return type argument handling in Flow. Can reproduce.

**Comment by Thom1729** [comment] 2021-06-21 19:29
Should be fixed in v11.0.1. Thanks for the report.

**Comment by jacargentina** [comment] 2021-06-22 13:41
v11.0.1 installed. Not working yet.

<img width="457" alt="Captura de Pantalla 2021-06-22 a la(s) 10 40 19" src="https://user-images.githubusercontent.com/517228/122934910-51e3ff00-d346-11eb-8a64-9d36e943c0a2.png">


<img width="693" alt="Captura de Pantalla 2021-06-22 a la(s) 10 40 27" src="https://user-images.githubusercontent.com/517228/122934946-56101c80-d346-11eb-9915-2a12603f4adb.png">

**Comment by Thom1729** [comment] 2021-06-22 13:50
Can you paste the errant code as text?

**Comment by jacargentina** [comment] 2021-06-22 13:57
const ItemLookupScreen = (props: any): React.Node => {
  const data = useContext(DataContext);
  const navigation = useNavigation();
  const {
    request,
    loading,
    error,
    result: apiResult,
  } = useApiAuth(data.apiConfig, 'Items');

  const { setParam, params, ...paginated } = usePaginated(Initial, apiResult);
  const [textFilter, setTextFilter] = useState('');

  useEffect(() => {
    setParam({ filtroTexto: textFilter });
  }, [setParam, textFilter]);

  const seleccionar = (item: ItemDTO) => {
    navigation.navigate('EditarItem', {
      item,
    });
  };

  useEffect(() => {
    request(params);
  }, [request, params]);

  return null;
}

**Comment by Thom1729** [comment] 2021-06-22 14:53
v11.0.2 is out with a couple more Flow fixes. Please let me know if this fixes it.

**Comment by darve** [comment] 2021-06-23 10:21
Hello friends,

I'm running the latest version (v11.0.2) and the syntax highlight is still broken for me:

![image](https://user-images.githubusercontent.com/1042366/123080726-24b25200-d415-11eb-8701-e4e6ec0cb456.png)

**Comment by Thom1729** [comment] 2021-06-23 14:11
Can you post the complete text of the file? Or a complete working example?

**Comment by Thom1729** [comment] 2021-06-23 14:39
@darve I can't reproduce. Since highlighting is messed up at the beginning of that excerpt, it probably means that the error occurs in other code before the excerpt. Without seeing more of the code, I can't troubleshoot it.

**Comment by darve** [comment] 2021-06-23 14:55
It’s strange because the highlighting is broken on the entire repo, the build is green lights across the board. I’ll investigate and report back…

**Comment by Thom1729** [comment] 2021-06-23 23:39
@darve Is this still broken, or did it turn out to be something else?

**Comment by maullerz** [comment] 2021-06-24 09:57
Hi @Thom1729 
I just found that last 2 versions also changed the color of `reserved words` like const / let / function
Before
<img width="360" alt="Screenshot 2021-06-24 at 12 56 41" src="https://user-images.githubusercontent.com/5295025/123243487-bd1b0600-d4eb-11eb-81b1-9ec4d8704772.png">

After
<img width="395" alt="Screenshot 2021-06-24 at 12 56 09" src="https://user-images.githubusercontent.com/5295025/123243504-c1dfba00-d4eb-11eb-8e25-b885b86da815.png">

**Comment by Thom1729** [comment] 2021-06-24 13:44
This is the deliberate result of changes to the consensus on scope naming. In the guidelines, `storage.type` is used for type names in C-style declarations like `int foo;`. Since then, `storage.type` has generally been used for non-type variable declaration keywords like `const`. After much discussion, the community decided to reserve `storage.type` for types and use `keyword.declaration` for other declaratory keywords.

If you prefer the old behavior, you can modify your color scheme to highlight `keyword.declaration` the same as `storage.type`.

**Comment by darve** [comment] 2021-06-24 14:14
It would appear it is working as intended then, because I have the same issue as @maullerz... I just assumed it was doing that because something was broken because it looks mighty strange!

**Closed** 2021-06-24 16:25 UTC

**Comment by maullerz** [comment] 2021-06-24 21:40
Awesome, thanks!
Simple fix for my `Monokai Phoenix.tmTheme` and voila! Here is my previous beloved color scheme 🚀 

What i was need:
```
<dict>
  <key>name</key>
  <string>keyword.declaration</string>
  <key>scope</key>
  <string>keyword.declaration</string>
  <key>settings</key>
  <dict>
    <key>foreground</key>
    <string>#66D9EF</string>
  </dict>
</dict>
```

PS:
more info for customization here:
https://www.sublimetext.com/docs/scope_naming.html#keyword
https://www.sublimetext.com/docs/scope_naming.html#storage
