### ISSUE TITLE
Comments on JSX not working properly

### ISSUE THREAD

**Issue by franciscolourenco** [babel/babel-sublime#331] opened 2017-06-02 12:24 UTC
Commenting doesn't seem to be working correctly. 

Code:
```js
export default class MyComponent extends Component {
  render: () {
    return (
      <div>
        // <div>
          <div>
            
          </div>
        </div>
      </div>
    )
  }
}
```
Scope:
```
source.js 
meta.class.js 
meta.class.property.js 
meta.group.braces.curly.js 
meta.group.braces.round.js 
meta.jsx.js
```

Any ideas?

**Comment by aristidesfl** [comment] 2017-06-12 21:06
This is caused by having the default `Javascript` package installed. The package is necessary for  JSON syntax highlighting. Is there a possible fix for this, or will the javascript comment preferences alway override the Babel ones?

**Comment by fr0m** [comment] 2017-11-23 06:20
babel-sublime could provide JSON syntax highlight, so the Javascript package is not necessary.

**Comment by borela** [comment] 2018-01-15 03:41
Try FJSX15 https://github.com/borela/naomi there will be no need to disable the core Javascript package.

**Comment by ellipticaldoor** [comment] 2018-02-12 12:38
Any fix for this?

**Comment by brianfeister** [comment] 2018-02-23 21:31
I'm looking for a fix for this as well

**Comment by borela** [comment] 2018-03-10 22:25
Figured out how to make this work https://github.com/borela/naomi, it turns out it's not as easy as it looks and it required additional meta scopes and this monstrosity https://github.com/borela/naomi/blob/master/plugin/ToggleJsxComment.py (I'll clean up the code in a couple of days) to detect the correct comment type to use and to "feel right".

The latest versions already ship with the plugin, .

**Comment by Thom1729** [comment] 2020-01-20 03:11
This should be fixed in v10.0.0-beta.1. See #379 for more information on the new release. Please report any problems with v10 in a new issue.

**Closed by Thom1729** 2020-01-20 03:11 UTC
