### ISSUE TITLE
Support empty tags

### ISSUE THREAD

**Issue by zamponotiropita** [babel/babel-sublime#386] opened 2020-05-20 20:39 UTC
https://reactjs.org/docs/fragments.html#short-syntax

**Comment by epbarger** [comment] 2020-06-04 23:41
This would be SUPER helpful! Empty tags completely break the highlighting :(

**Comment by Thom1729** [comment] 2020-06-05 00:00
Duplicate of #368. Closing because it's fixed in the prerelease. See #379 for more info.

**Closed by Thom1729** 2020-06-05 00:00 UTC
Labels: duplicate
