### ISSUE TITLE
I can't use the constant variable on sublime text 3- Windows

### ISSUE THREAD

**Issue by KIngsleyOkb** [babel/babel-sublime#345] opened 2017-10-23 01:13 UTC
I have downloaded  "babel" from my package Control and still, I can't get rid of the Error assigned to the constant variable- cont 
I am using JavaScript, what should I do?

**Comment by Thom1729** [comment] 2020-01-19 22:03
I'm closing this issue because it's not clear what the problem is. If you're still having a problem with babel-sublime, please reopen the issue and add more detail, including example code.

**Closed by Thom1729** 2020-01-19 22:03 UTC
