### ISSUE TITLE
commenting JS does not work in sublime

### ISSUE THREAD

**Issue by seven-deuce** [babel/babel-sublime#396] opened 2021-04-11 11:28 UTC
Hi
In last few days I have realized that commenting JS files with control+/ does not work in sublime, I tried everything and it didn't work, until I removed babel and installed JS Custom and in View > Syntax > User , chose javascript and then the commenting started to work.
Which means, this is a problem with the new babel package for sublime

**Comment by Thom1729** [comment] 2021-04-11 13:41
That's odd, particularly because the new babel syntax is literally built from JS Custom. Are you by any chance disabling the built-in JavaScript package?

**Comment by seven-deuce** [comment] 2021-04-11 14:11
nope, please give it a try. When the Babel syntax is active, in the js files, you cannot comment by ctrl+/
even doesn't work from the edit menu. If you choose the JS Custom syntax for js files, then it works. I started to have this problem 2 days ago. I also have Prettier on, but I don't think it is related to that

**Comment by Thom1729** [comment] 2021-04-11 14:35
I just tested it in a clean environment and could not reproduce.

The release went out Friday night at 22:53 UTC. Do you know for sure whether you observed the issue before or after updating?

What Sublime version are you running, and what packages do you have installed?

Does the problem exist if you temporarily disable Prettier?

**Comment by seven-deuce** [comment] 2021-04-11 14:47
I am using the sublime text 3
I had removed Babel, I installed it again, this time it worked!
Then I removed JS Custom, Then the problem happened again, not possible to comment the code!
Next, I installed JS Custom again, I got this error after adding the package:
![image](https://user-images.githubusercontent.com/40258654/114308845-41b5d500-9af6-11eb-9f5c-f71ab638d109.png)
But the commenting was possible after that. SO babel without that package does not work correctly

**Comment by Thom1729** [comment] 2021-04-11 15:13
Something odd is going on.

The core JavaScript package provides handling for comments in plain JavaScript. This should work for any syntax with the `source.js` scope, including Babel.

JS Custom provides a duplicate of that commenting functionality that also applies to other scopes like `source.ts`. It also provides special handling for JSX comments.

Babel only provides handling for JSX comments. It doesn't need to handle regular JavaScript comments because the core JavaScript package already does.

If you have disabled the JavaScript package, then what you're seeing makes sense. Without the core package, Babel's syntax will use JS Custom's commenting rules, and without either of them it won't know how to comment plain JavaScript. Are you absolutely sure that you haven't ignored the JavaScript package?

Can you run the following in the console and post the output?

```
sublime.load_settings('Preferences.sublime-settings').get('ignored_packages')
```

**Comment by seven-deuce** [comment] 2021-04-11 15:26
Yes you are right. Javascript is included in my ignored packages
I don't remember when it I added that, so it was working all fine even when it was there
After removing the JS Custom, now commenting works with babel alone.
It was weird how it has worked all up to a few days ago.
Thank you for the help

**Comment by Thom1729** [comment] 2021-04-11 15:30
No problem!

I wonder if I should just duplicate all of the commenting and symbol list stuff from the core package. This package's readme used to suggest disabling the core package even though it never provided all of those pieces, and there are probably lots of users out there who disabled the core package at some point and are having problems.

**Closed by Thom1729** 2021-04-11 15:30 UTC

**Comment by seven-deuce** [comment] 2021-04-11 16:02
I think you better duplicate them, the package should be stand-alone. There is no harm in duplication
