### ISSUE TITLE
Multiline arguments in arrow functions

### ISSUE THREAD

**Issue by simov** [babel/babel-sublime#361] opened 2018-06-23 11:44 UTC
When using arrow functions both the function name and the arguments lose syntax highlighting when the arguments are on multiple lines:

![screenshot from 2018-06-23 14-39-37](https://user-images.githubusercontent.com/1694112/41809279-858a867e-76f3-11e8-81cf-cc07e29d6468.png)

**Comment by Thom1729** [comment] 2018-06-23 14:35
This is a limitation of Sublime's parsing engine. See https://github.com/SublimeTextIssues/Core/issues/2241.

**Comment by Thom1729** [comment] 2020-01-24 15:50
Closing as a duplicate of #340.

**Closed by Thom1729** 2020-01-24 15:50 UTC
