### ISSUE TITLE
goto definition for es6 methods

### ISSUE THREAD

**Issue by vanntastic** [babel/babel-sublime#59] opened 2015-03-06 16:26 UTC
goto definitions doesn't seem work for es6 methods, however they do work for standard es5 methods. Is there anything that I can look at to make it work?

Thanks!

**Comment by zertosh** [comment] 2015-03-06 19:42
I'll be honest, I only use "Goto Symbol", and figuring out "Goto Symbol in Project" was just an extension of that. I have no idea how "Goto Definition" is supposed to work. I tried it with some ES5 files, using the stock JavaScript syntax, and I'm still not sure I understand what the expected behavior is. Can you help me understand? Maybe point me to some docs?

According to [Symbols — Sublime Text Unofficial Documentation](http://sublime-text-unofficial-documentation.readthedocs.org/en/latest/reference/symbols.html), it should just work if the symbols are defined - which they are, since it they work for "Goto Symbol" and "Goto Symbol in Project".

**Comment by vanntastic** [comment] 2015-03-07 19:02
hmmm, I'll see if I can take a look at what other packages to see what they're doing, but I'm not familiar enough with sublime text language files. I'll keep you posted if I find anything.

**Comment by zertosh** [comment] 2015-03-15 05:04
Any progress @vanntastic?

**Comment by vanntastic** [comment] 2015-03-16 14:58
@zertosh I haven't had a chance to dig into it much, it's not a big deal - feel free to close this if you want

**Comment by zertosh** [comment] 2015-04-11 21:56
@vanntastic I think that maybe after https://github.com/babel/babel-sublime/pull/75, this might be fixed by turning off the stock JavaScript package. Checkout [advanced usage](https://github.com/babel/babel-sublime#advanced-usage) and let me know if you can give it a try.

**Comment by felipehummel** [comment] 2015-07-16 15:06
Anyone manage to make this work?

**Comment by zertosh** [comment] 2015-07-18 00:49
@felipehummel I just publish v7.2.0 with https://github.com/babel/babel-sublime/commit/abd5c13c3bdf7042d2c7a810765357f165232475. I think it fixes "Goto Definition" - it seems like it works, but I have no idea how it's supposed to work. Can you let me know if it fixes it?

**Comment by zertosh** [comment] 2015-07-19 12:58
It seems to be working for me. So I'm going to close this. Please open a new issue if you're still having problems.

**Comment by felipehummel** [comment] 2015-07-20 15:30
The ES6 functions are now working with Go-to definition! :+1: 
But I just realized that variables (`const`, `let` and `var`) are not considered symbols, so you can't go-to a definition of a variable, actually you can't also Go-to them (using Go-to Symbol feature).

Just to clarify why Go-to definition is very nice: 
The go-to definition is a common feature of more robust IDEs. Sublime managed to include a good enough version of it (considering it doesn't create AST or any intelligence over the code).
Using IntelliJ Idea or Sublime, the Go-to Definitions is one of my main ways of navigating code.

For example, you're using a function `const x = actions.reloadItems()`, you can put the caret on any character of `reloadItems` and press the Go-to definition shortcut and it will take to wherever place in your code that symbol was defined. Places like: `const reloadItems = ...`, `var reloadItems = ...`, `function reloadItems(...)`, `reloadItems() { ... }`, `class reloadItems ...`.

In my case I'm working with React. So another example is to put the caret on the name of a component like: `<MyListComponent style=.... /> ` and go to where the component was defined. (currently it works if it was defined as a class instead of `const MyListComponet = React.createClass({...})`)
Depending of the workflow you're on, you can Go-to-definition your way around the code with lesser need of manually opening files or changing tabs.

Thanks!

**Comment by zertosh** [comment] 2015-07-24 14:06
Thanks @felipehummel, I've re-opened the issue so I can take a closer look.

**Comment by ddemolina** [comment] 2015-09-14 12:23
When I use go to definition Sublime shows me a list whith the definition but shows all places where the method is used.  
Shows only the definition its a better solution. Thanks

**Comment by zertosh** [comment] 2015-10-06 07:49
I found a solution to this - I'll push a fix soon

**Comment by ddemolina** [comment] 2015-10-06 08:09
Only I want to clarify there are two diferents problems. One is related to "Go to definition' (F12) which I commented in previous message. 
The other issue is related to "Go to Symbol" (Ctrl +R). I've seen you has closed #179 and referenced from #59
Maybe, internally, its the same but I only want to clarify they are different problems in order to avoid missunderstandings.
Thanks

**Comment by zertosh** [comment] 2015-10-07 07:33
I just published v8.4.0, for any of this to work you need to disable the stock JavaScript package - sorry, not my fault. This is the current status:

* The Goto Symbol panel looks really clean - no extra function keyword, no arrow functions.
* If from a short-method's name up to the start `{` are not on the same line, it's not gonna show up. It's complicated. I'm working on it - it works in #183, but that has its own problems.
* Some `var`/`let`/`const` work in #183 but again, it's complicated.

**Closed** 2016-01-02 04:11 UTC
Labels: help wanted
